import {
  ModeEnum,
  IndexTypeEnum,
  DependencyComponentEnum,
  RefineValueEnum,
} from '@/types/sizing';
import {
  VECTOR_RANGE_CONFIG,
  DIMENSION_RANGE_CONFIG,
  MAX_NODE_DEGREE_RANGE_CONFIG,
  SEGMENT_SIZE_OPTIONS,
  INDEX_TYPE_OPTIONS,
  DEPENDENCY_COMPONENTS,
  MODE_OPTIONS,
  N_LIST_RANGE_CONFIG,
  M_RANGE_CONFIG,
  MAXIMUM_AVERAGE_LENGTH,
  REFINE_OPTIONS,
  helmCodeExample,
  operatorCodeExample,
  HELM_CONFIG_FILE_NAME,
  OPERATOR_CONFIG_FILE_NAME,
  dockerComposeExample,
} from '@/consts/sizing';
import {
  memoryAndDiskCalculator,
  rawDataSizeCalculator,
  $10M768D,
  $50M768D,
  $500M768D,
  $100M768D,
  $1B768D,
  dependencyCalculator,
  clusterNodesConfigCalculator,
  standaloneNodeConfigCalculator,
  formatNumber,
  unitBYTE2Any,
  milvusOverviewDataCalculator,
  dependencyOverviewDataCalculator,
  helmYmlGenerator,
  operatorYmlGenerator,
  formatOutOfCalData,
} from '@/utils/sizingTool';
import { SizingVersionConfig } from '@/parts/sizingCommon';

export const sizingV3Config: SizingVersionConfig = {
  version: 'v3',
  supportsRabitq: true,
  supportsWoodpecker: true,
  extraNodeKey: 'streamNode',
  extraNodeLabelKey: 'setup.milvus.streamNode',
  extraNodeTipKey: 'setup.milvus.streamNodeTip',
  types: {
    ModeEnum,
    IndexTypeEnum,
    DependencyComponentEnum,
    RefineValueEnum,
  },
  consts: {
    VECTOR_RANGE_CONFIG,
    DIMENSION_RANGE_CONFIG,
    MAX_NODE_DEGREE_RANGE_CONFIG,
    SEGMENT_SIZE_OPTIONS,
    INDEX_TYPE_OPTIONS,
    DEPENDENCY_COMPONENTS,
    MODE_OPTIONS,
    N_LIST_RANGE_CONFIG,
    M_RANGE_CONFIG,
    MAXIMUM_AVERAGE_LENGTH,
    REFINE_OPTIONS,
  },
  utils: {
    memoryAndDiskCalculator,
    rawDataSizeCalculator,
    $10M768D,
    $50M768D,
    $500M768D,
    $100M768D,
    $1B768D,
    dependencyCalculator,
    clusterNodesConfigCalculator,
    standaloneNodeConfigCalculator,
    formatNumber,
    unitBYTE2Any,
    milvusOverviewDataCalculator,
    dependencyOverviewDataCalculator,
    helmYmlGenerator,
    operatorYmlGenerator,
    formatOutOfCalData,
  },
  resultConsts: {
    helmCodeExample,
    operatorCodeExample,
    HELM_CONFIG_FILE_NAME,
    OPERATOR_CONFIG_FILE_NAME,
    dockerComposeExample,
  },
};
