import React, { useState } from "react";
import { graphql } from "gatsby";
import { useI18next } from "gatsby-plugin-react-i18next";
import "./index.less";
import { useWindowSize } from "../http/hooks";
import Layout from "../components/layout";
import Signup from "../components/signup";
import HomeBanner from "../components/home/banner";
import { CustomizedSnackbars } from "../components/snackBar";
import CloudIcon from "../images/home/cloud.svg";
import CommandIcon from "../images/home/command.svg";
import SearchIcon from "../images/home/search.svg";

// markup
const IndexPage = () => {
  const { t } = useI18next();

  const currentSize = useWindowSize();
  const isMobile = ["phone", "tablet"].includes(currentSize);

  const [snackbarConfig, setSnackbarConfig] = useState({
    open: false,
    type: "info",
    message: "",
  });

  const handleOpenSnackbar = ({ message, type }) => {
    setSnackbarConfig({
      open: true,
      type,
      message,
    });
  };

  const handleCloseSnackbar = () => {
    setSnackbarConfig({
      open: false,
      type: "info",
      message: "",
    });
  };

  return (
    <main className="homepage">
      <Layout darkMode={true} t={t}>
        <HomeBanner />

        <section className="section2 col-12 col-8 col-4">
          <h2>Fuel your machine learning deployment</h2>
          <h5>
            Store, index, and manage massive embedding vectors generated by deep
            neural networks and other machine learning (ML) models.
          </h5>
          <ul className="features">
            <li>
              <img src={CloudIcon} alt="cloud" />
              <h4>Cloud-native</h4>
              <p>
                Cloud-native architectures help deliver breakthrough efficiency
                and agility.
              </p>
            </li>
            <li>
              <img src={SearchIcon} alt="search" />
              <h4>Vector similarity search</h4>
              <p>
                Vector search paired with attribute filtering to leverage the
                synergy of various data types.
              </p>
            </li>
            <li>
              <img src={CommandIcon} alt="command" />
              <h4>Developer first</h4>
              <p>
                Milvus provides comprehensive multi-language SDKs for your ML
                applications.
              </p>
            </li>
          </ul>
        </section>
        <Signup isMobile={isMobile} callback={handleOpenSnackbar} />
        <CustomizedSnackbars
          open={snackbarConfig.open}
          type={snackbarConfig.type}
          message={snackbarConfig.message}
          handleClose={handleCloseSnackbar}
        />
      </Layout>
    </main>
  );
};

export const query = graphql`
  query ($language: String!) {
    locales: allLocale(filter: { language: { eq: $language } }) {
      edges {
        node {
          data
          language
          ns
        }
      }
    }
  }
`;

export default IndexPage;
