import classes from './index.module.less';
import pageClasses from '../../../styles/responsive.module.less';
import clsx from 'clsx';

export default function HomeFeature() {
  return (
    <section
      className={clsx(pageClasses.col12, classes.featureSectionContainer)}
    >
      <h2>Fuel your machine learning deployment</h2>
      <h5>
        Store, index, and manage massive embedding vectors generated by deep
        neural networks and other machine learning (ML) models.
      </h5>
      <ul className={classes.features}>
        <li>
          <img src="/images/home/easy.svg" alt="Easy to Use" />
          <h4>Easy to Use</h4>
          <p>
            With Milvus vector database, you can create a large scale similarity
            search service in less than a minute. Simple and intuitive SDKs are
            also available for a variety of different languages.
          </p>
        </li>
        <li>
          <img src="/images/home/fast.svg" alt="Blazing Fast" />
          <h4>Blazing Fast</h4>
          <p>
            Milvus is hardware efficient and provides advanced indexing
            algorithms, achieving a 10x performance boost in retrieval speed.
          </p>
        </li>
        <li>
          <img src="/images/home/available.svg" alt="Highly Available" />
          <h4>Highly Available</h4>
          <p>
            Milvus vector database has been battle-tested by over a thousand
            enterprise users in a variety of use cases. With extensive isolation
            of individual system components, Milvus is highly resilient and
            reliable.
          </p>
        </li>
        <li>
          <img src="/images/home/scale.svg" alt="Highly Scalable" />
          <h4>Highly Scalable</h4>
          <p>
            The distributed and high-throughput nature of Milvus makes it a
            natural fit for serving large scale vector data.
          </p>
        </li>
        <li>
          <img src="/images/home/cloud.svg" alt="Cloud-native" />
          <h4>Cloud-native</h4>
          <p>
            Milvus vector database adopts a systemic approach to cloud-nativity,
            separating compute from storage and allowing you to scale both up
            and out.
          </p>
        </li>

        <li>
          <img src="/images/home/rich.svg'" alt="Feature-rich" />
          <h4>Feature-rich</h4>
          <p>
            Support for various data types, enhanced vector search with
            attribute filtering, UDF support, configurable consistency level,
            time travel, and more.
          </p>
        </li>
      </ul>
    </section>
  );
}
